### ISSUE TITLE
How to send payment correctly?

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore-wallet-client#277]
Dear Sirs,

I tried to send funds to address:

```
var tx={toAddress:'myDqnzFGgmG6e5mvCHJgCe72HkaTxKd7rN', amount:4000, message:'Test'};

client.sendTxProposal(tx, function(err, proposal)
{
    if (err) 
    {
        console.log('error: ',err); 
        return
    };
    console.log('trxn: ', proposal);
});

```
and now I have funds locked and test wallet does not receive them.
Seems I don't complete transaction.
Could you point me please the correct way to make payment please?

Thanks,
Igor

**Comment by dabura667** [comment]
There are 3 steps to every transaction.

1. Create the proposal. (Does not sign)
2. Sign the proposal (This must be done by m members ("m-of-n" so "2-of-3" means 2 members must perform this step)
3. Send the signed proposal (aka transaction)

You have the proposal sitting on BWS waiting for you to sign. Now just sign the proposal and send...

(I am not sure, but I think if you sign the proposal and your signature is the m'th signature it might automatically send... not too sure)

**Comment by igorvlassov** [comment]
Dear @dabura667 
Thanks a lot but need clarification still:
1 - I checked API code and seems createTxProposal & sendTxProposal functions make almost the same. Could you point to preferable function for proposal creation?
2 - I managed to get proposal with getTxProposals and I signed it with signTxProposal but seems it there in BWS still so
3 - With what function should I send proposal?

Thanks in advance,
Igor

**Comment by isocolsky** [comment]
To expando on what @dabura667 explained:
In recent versions of BWS/BWC, a new flow for tx proposal creation was introduced. These are the steps:
1) Create the proposal (using `createTxProposal` instead of the deprecated `sendTxProposal`). The proposal will only be accessible to the creator and no funds will get locked.
2) Publish the proposal (using `publishTxProposal`) so other copayers can actually see & sign/reject the proposal. It is at this time that funds get locked.
3) Collect M signatures (using `signTxProposal`).
4) Broadcast the accepted proposal (using `broadcastTxProposal`).
Hope this helps.

**Comment by igorvlassov** [comment]
Dear @isocolsky 
Thanks a lot for the explanation, things are clear for me now!

**Comment by o-ayoub** [comment]
Can any one provide an example of creating transaction, publish and sign transaction;

Thanks
