### ISSUE TITLE
About transaction messages

### ISSUE THREAD

**Issue by frz-dev** [bitpay/bitcore-wallet-client#338]
I have some doubts about the 'message' field, included in the options to the createTxProposal function.

Are we talking about Bitcoin network messages, like those described [here](https://bitcore.io/api/p2p/messages)? If not, what are they, and how are they employed?
Also, where are these messages stored?

**Comment by dabura667** [comment]
Messages are stored in the BWS server database encrypted by the wallet encryption key.

Therefore, the BWS server maintainer can not see any of the messages, but the copayers can see it because they have the decryption keys.

These messages only exist on the BWS server, so if the BWS server disappears. So does all your messages.

Wallets can be restored outside of BWS, but messages are tied to the BWS server.

Do you understand?

**Comment by frz-dev** [comment]
Perfectly! Thanks for the explaination.
