### ISSUE TITLE
Need help: What is m and n?

### ISSUE THREAD

**Issue by zekylaf** [bitpay/bitcore-wallet-client#346]
I have seen **m** and **n** in the _createWallet_ method:

`API.createWallet(walletName, copayerName, m, n, opts, opts.network, opts.walletPrivKey, opts.id, opts.withMnemonics, cb)`

An error through me that:
- **m** is requiredCopayers 
- **n** is totalCopayers

My qustion is: what is the relation of m and n with the status of the wallet? 

Thanks in advance!

**Comment by dabura667** [comment]
m=1;n=1 is a normal single signature wallet (address starts with 1)

m <= n must always be true.

m=2;n=3 is a "2 of 3" multisig, where 3 public keys are generated to create the address (starts with a 3) and of those 3 public keys, each transaction needs signatures from at least 2 out of those 3 keys in order to send bitcoin.

**Comment by zekylaf** [comment]
First of all, thanks @dabura667 for answer.

So, If I create a "2 of 3" multisig wallet, Need I to join 3 different copayers in order to change the wallet's status to "Complete"?

Thanks

**Comment by dabura667** [comment]
Yes. Currently you can not "join" a multisig wallet from the same app. (we obviously know you are not 3 people :-P)

The idea is that 3 people each use their phones. One "creates" the wallet, and the other two "join" it. Then it is complete and everyone can create and view addresses for the wallet.

However, each person will have to write down their own SEPARATE 12 word backup phrase, so be careful.

(Protip: When using the Chrome App, if you create multiple "profiles" in your Chrome settings and open Copay from these different profile's windows, you can actually create a multisig locally on the same computer, but it is not recommended (it defeats the purpose))

Also, be aware that using multisig will increase the cost of each transaction significantly. Paying almost DOUBLE the fees of a normal 1 of 1 wallet. (This is because bitcoin network charges fees based on data size of transactions, and ex. 2-of-3 multisig needs to include 3 pubkeys (or however many you choose) and 2 signatures whereas 1 of 1 only needs to include 1 of each. which adds up to larger transaction data)

**Comment by zekylaf** [comment]
Thanks again @dabura667 

Have a merry christmas!
