### ISSUE TITLE
Balance blocked

### ISSUE THREAD

**Issue by aderiver** [bitpay/bitcore-wallet-client#367]
hi 

Currently I have a balance blocked in my wallets, were the result of transactions that failed to sign. How can I unblock this balance?

thanks

**Comment by matiu** [comment]
you can delete the transaction proposals, to release the coins.

On Apr 12, 2017 18:10, "Javier Adrian Rivera Perez" <
notifications@github.com> wrote:

hi

Currently I have a balance blocked in my wallets, were the result of
transactions that failed to sign. How can I unblock this balance?

thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitpay/bitcore-wallet-client/issues/367>, or mute the
thread

**Comment by aderiver** [comment]
hi Matiu;

thanks for you answer,  Solve my problem with the method removeTxProposal

very much thanks
