### ISSUE TITLE
How to Get Notifications on Incoming Transactions

### ISSUE THREAD

**Issue by Chibuzo** [bitpay/bitcore-wallet-client#377]
I built an exchange platform using BWS and the wallet-client. I know when a]my user sends btc so I log it in the database. However, incoming transactions from other bitcoin exchanges or website do not get saved on my database.
How can I receive or listen for notifications for incoming btc transfer on a wallet?

Thank you

**Comment by dabura667** [comment]
Look at API.prototype.initialize

API is also an event emitter, so listen for the events that happen whenever a notification happens, and in the callback write to the database.

**Comment by Chibuzo** [comment]
Hi @dabura667, I tried setting up notification with the following snippet you shared on another thread, but it didn't work for me. I got the error: Ïllegal State.

`client.initialize({}, function(err){
    if (err) 
    {
          console.log('error: ', err);
          return;
    } 
    client.on('notification', function(notification) {
        console.log('A Wild Notification Appeared!')
        console.dir(notification);
    });
    console.log("initialized");
});
console.log("end");`

It seems a wallet would be open for the code to work, I'm not sure.

However, In my case, I run a wallet service for users. I need an event listener that would signal any time a transaction happens in any of the wallets on my BWS.

If you can show me a code snippet I would be most grateful.

Thank you @dabura667

**Comment by jeshan** [comment]
For a working example, you can check the Copay source code. It has the feature that you're describing.

**Comment by Chibuzo** [comment]
Thanks @jeshan for the suggestion.
I've gone through Copay source code without seeing any useful example.

Please can you point me to a particular file where I can find an example?

NB: Copay used Angular, I didn't use Angular.

Thank you

**Comment by jeshan** [comment]
@Chibuzo 
The BitPay guys used an old project of their own to handle this called `angular-bitcore-wallet-client` (which is the predecessor to this one).

Check the following file after building the Copay source code:
`angular-bitcore-wallet-client/angular-bitcore-wallet-client.js`

You won't find this file just by browsing the github repo since it's a generated file and ignored by git). So, you'll have to run the copay app locally first (or check the repo https://github.com/bitpay/angular-bitcore-wallet-client).
As @dabura667 correctly said, you'll see how to use API.prototype.initialize there. This class is a full(?) example of how to use the API.

```javascript
API.prototype.initialize = function(opts, cb) {
  $.checkState(this.credentials);

  var self = this;

  self.notificationIncludeOwn = !!opts.notificationIncludeOwn;
  self._initNotifications(opts);
  return cb();
};
```

Following the _initNotifications method will lead you to the following:
```javascript
API.prototype._fetchLatestNotifications = function(interval, cb) {
  var self = this;

  cb = cb || function() {};

  var opts = {
    lastNotificationId: self.lastNotificationId,
    includeOwn: self.notificationIncludeOwn,
  };

  if (!self.lastNotificationId) {
    opts.timeSpan = interval + 1;
  }

  self.getNotifications(opts, function(err, notifications) {
    if (err) {
      log.warn('Error receiving notifications.');
      log.debug(err);
      return cb(err);
    }
    if (notifications.length > 0) {
      self.lastNotificationId = _.last(notifications).id;
    }

    _.each(notifications, function(notification) {
      self.emit('notification', notification);
    });
    return cb();
  });
};
```

Pay attention to the **self.emit('notification', notification);** statement.

This notification event will be received in the Copay code at
`src/js/services/profileService.js` :

```javascript
wallet.on('notification', function(n) {

        $log.debug('BWC Notification:', n);

        if (n.type == "NewBlock" && n.data.network == "testnet") {
          throttledBwsEvent(n, wallet);
        } else newBwsEvent(n, wallet);
});
```

Based on the above, you can plug your own logic. Copay indeed uses Angular but what you want is not particularly to the framework. Even if you don't understand Angular, you shouldn't have any problem understanding the relevant code.

**Comment by Chibuzo** [comment]
Thank you very much @jeshan. You did more than I asked for.

I now understand how notification works.

**Comment by jeshan** [comment]
Glad it helped. Feel free to close the issue.
